- id: blocking-comment
  name: Prevent on Blocking Comments
  description: This hook prevents commits by checking for blocking comments in the code.
  entry: check-for-blocking-comments
  language: python
