- id: blocking-comment
  name: Prevent on Blocking Comments
  description: This hook prevents commits by checking for blocking comments in the code.
  entry: python pre-commit-blocking-comment.py
  language: python
